# Generated by Django 5.0.7 on 2024-08-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_church_primary_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
