# Generated by Django 5.0.7 on 2024-09-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_people_spouse_recruit_and_more'),
    ]

    
