# Generated by Django 5.0.7 on 2024-08-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_people_affiliated_church'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='mission_pastor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='mission_pastor_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='primary_contact_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='primary_contact_phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='senior_pastor_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='senior_pastor_phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
