# Generated by Django 5.0.7 on 2024-09-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_people_spouse_recruit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',            
        ),
    ]
