# Generated by Django 5.0.7 on 2024-09-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_people_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='church_pipeline',
            field=models.CharField(choices=[('PROMOTION', 'PROMOTION'), ('INFORMATION', 'INFORMATION'), ('INVITATION,', 'INVITATION,'), ('CONFIRMATION', 'CONFIRMATION'), ('EN42', 'EN42'), ('AUTOMATED', 'AUTOMATED')], default='UNKNOWN', max_length=100),
        ),
        migrations.AlterField(
            model_name='people',
            name='people_pipeline',
            field=models.CharField(blank=True, choices=[('PROMOTION', 'PROMOTION'), ('INFORMATION', 'INFORMATION'), ('INVITATION,', 'INVITATION,'), ('CONFIRMATION', 'CONFIRMATION'), ('EN42', 'EN42'), ('AUTOMATED', 'AUTOMATED')], max_length=100, null=True),
        ),
    ]
