# Generated by Django 5.0.7 on 2024-08-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_church_mission_pastor_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AlterField(
            model_name='people',
            name='people_pipeline',
            field=models.CharField(blank=True, choices=[('contacted', 'Contacted'), ('mission vision', 'Mission Vision'), ('conversations', 'Conversations'), ('potential recruit', 'Potential Recruit'), ('handed off', 'Handed Off')], max_length=100, null=True),
        ),
    ]
