# Generated by Django 5.0.7 on 2024-09-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_church_church_pipeline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='people_pipeline',
            field=models.CharField(blank=True, choices=[('PROMOTION', 'PROMOTION'), ('INFORMATION', 'INFORMATION'), ('INVITATION,', 'INVITATION,'), ('CONFIRMATION', 'CONFIRMATION'), ('AUTOMATED', 'AUTOMATED')], max_length=100, null=True),
        ),
    ]
