# Generated by Django 5.0.7 on 2024-09-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_people_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
