# Generated by Django 5.0.7 on 2024-08-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_people_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='church_pipeline',
            field=models.CharField(choices=[('COLD', 'COLD'), ('WARM', 'WARM'), ('REPEATED FOLLOWUP', 'REPEATED FOLLOWUP'), ('MISSION VISION', 'MISSION VISION'), ('EN42', 'EN42')], default='UNKNOWN', max_length=100),
        ),
    ]
