# Generated by Django 5.0.7 on 2024-08-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_people_people_pipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='people_pipeline',
            field=models.CharField(blank=True, choices=[('contacted', 'Contacted'), ('mission-vision', 'Mission Vision'), ('conversations', 'Conversations'), ('potential-recruit', 'Potential Recruit'), ('handed-off', 'Handed Off')], max_length=100, null=True),
        ),
    ]
