# Generated by Django 5.0.7 on 2024-08-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_people_person_type_people_spouse_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
