# Generated by Django 5.0.7 on 2024-08-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_church_church_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='person_type',
            field=models.CharField(blank=True, choices=[('Student PR', 'Student PR'), ('Student', 'Student'), ('Webform', 'Webform'), ('Church PR', 'Church PR'), ('Couple PR', 'Couple PR'), ('Denied', 'Denied'), ('Intern', 'Intern')], max_length=100, null=True),
        ),
    ]
