# Generated by Django 5.0.7 on 2024-08-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_people_people_pipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='senior_pastor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='senior_pastor_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
