# Generated by Django 5.0.7 on 2024-08-15 14:36

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_church_senior_pastor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=contacts.models.get_image_path),
        ),
    ]
