# Generated by Django 5.0.7 on 2024-08-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_people_person_type'),
    ]

    operations = [        
        migrations.AddField(
            model_name='people',
            name='spouse_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='spouse_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='church_pipeline',
            field=models.CharField(choices=[('COLD', 'COLD'), ('WARM', 'WARM'), ('CONTACTED', 'CONTACTED'), ('MISSION VISION', 'MISSION VISION'), ('COMMITTED', 'COMMITTED'), ('EN42', 'EN42'), ('AUTOMATED', 'AUTOMATED')], default='UNKNOWN', max_length=100),
        ),
        migrations.AlterField(
            model_name='people',
            name='people_pipeline',
            field=models.CharField(blank=True, choices=[('uncontacted', 'Uncontacted'), ('contacted', 'Contacted'), ('mission-vision', 'Mission Vision'), ('conversations', 'Conversations'), ('potential-recruit', 'Potential Recruit'), ('automated', 'Automated')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='source',
            field=models.CharField(blank=True, choices=[('WEBFORM', 'WEBFORM'), ('INCOMING CALL', 'INCOMING CALL'), ('EMAIL', 'EMAIL'), ('INSTAGRAM', 'INSTAGRAM'), ('FACEBOOK', 'FACEBOOK'), ('X - TWITTER', 'X- TWITTER'), ('LINKEDIN', 'LINKEDIN'), ('COLD CALL', 'COLD CALL'), ('PERSPECTIVES', 'PERSPECTIVES'), ('REFERAL', 'REFERAL'), ('CIU', 'CIU'), ('CHURCH', 'CHURCH'), ('OTHER', 'OTHER')], max_length=100, null=True),
        ),
    ]
