# Generated by Django 5.0.7 on 2024-08-30 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_people_color'),
        ('contacts', '0008_remove_people_color_remove_people_spouse_recruit_and_more'),
    ]

    operations = [
    ]
