# Generated by Django 5.0.7 on 2024-08-30 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_merge_20240830_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='',
        ),
        
    ]
