runtime: python39
entrypoint: gunicorn -b :$PORT cg_mobilization.wsgi

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: "cg_mobilization.settings"