# fly.toml app configuration file generated for cg-mobilization-new-test on 2024-11-22T10:43:23-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cg-mobilization-new-test'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[statics]]
  guest_path = "/code/staticfiles"
  url_prefix = "/static"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
