# Generated by Django 4.2.14 on 2024-08-17 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('communication_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'Text'), ('meeting', 'Meeting'), ('video', 'Video Conference'), ('facebook', 'Facebook Messenger'), ('whatsapp', 'WhatsApp'), ('signal', 'Signal')], max_length=20)),
                ('summary', models.TextField()),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
