# Generated by Django 5.0.7 on 2024-08-15 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0008_alter_contact_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('communication_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'Text'), ('meeting', 'Meeting'), ('video', 'Video Conference'), ('facebook', 'Facebook Messenger'), ('whatsapp', 'WhatsApp'), ('signal', 'Signal')], max_length=20)),
                ('summary', models.TextField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='contacts.contact')),
            ],
        ),
    ]
