# Generated by Django 5.0.7 on 2024-08-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_log', '0002_remove_communicationlog_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationlog',
            name='communication_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'Text'), ('meeting', 'Meeting'), ('video', 'Video Conference'), ('facebook', 'Facebook Messenger'), ('whatsapp', 'WhatsApp'), ('signal', 'Signal')], max_length=20),
        ),
    ]
