# Generated by Django 5.0.7 on 2024-09-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('com_log', '0002_alter_comlog_options_rename_date_comlog_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comlog',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='comlog',
            old_name='date_created',
            new_name='date',
        ),
    ]
