# Generated by Django 5.0.7 on 2024-08-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('com_log', '0003_alter_communicationlog_communication_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationlog',
            options={'ordering': ['-date']},
        ),
    ]
