# Generated by Django 5.0.7 on 2024-08-21 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_log', '0003_handle_null_content_types'),
        ('contacts', '0004_alter_church_mission_pastor_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comlog',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.church'),
        ),
        migrations.AddField(
            model_name='comlog',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comlog',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comlog',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.people'),
        ),
    ]
