# Generated by Django 5.0.7 on 2024-08-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('com_log', '0004_comlog_church_comlog_follow_up_date_comlog_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comlog',
            name='church',
        ),
        migrations.RemoveField(
            model_name='comlog',
            name='follow_up_date',
        ),
        migrations.RemoveField(
            model_name='comlog',
            name='person',
        ),
        migrations.RemoveField(
            model_name='comlog',
            name='summary',
        ),
    ]
