# Generated by Django 5.0.7 on 2024-08-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('com_log', '0004_alter_communicationlog_options'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommunicationLog',
            new_name='ComLog',
        ),
    ]
