# Generated by Django 5.0.7 on 2024-08-26 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_log', '0005_remove_comlog_church_remove_comlog_follow_up_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comlog',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='comlog',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='comlog',
            name='direction',
            field=models.CharField(choices=[('Incoming', 'Incoming'), ('Outgoing', 'Outgoing')], default='Outgoing', max_length=10),
        ),
        migrations.AddField(
            model_name='comlog',
            name='interaction_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'Text'), ('meeting', 'Meeting'), ('video', 'Video Conference'), ('facebook', 'Facebook Messenger'), ('whatsapp', 'WhatsApp'), ('signal', 'Signal')], default='email', max_length=50),
        ),
        migrations.AddField(
            model_name='comlog',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='comlog',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comlog',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
