# Generated by Django 5.0.7 on 2024-08-17 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_log', '0005_rename_communicationlog_comlog'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comlog',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='comlog',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
