# Generated by Django 5.0.7 on 2024-08-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com_log', '0006_alter_comlog_options_rename_date_comlog_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comlog',
            name='interaction_type',
            field=models.CharField(max_length=20),
        ),
    ]
