# Generated by Django 5.0.7 on 2024-08-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='profile_thumbnails/'),
        ),
    ]
