# Generated by Django 5.0.7 on 2024-08-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
