# Generated by Django 5.0.7 on 2024-09-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_customuser_google_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='google_refresh_token',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
    ]
