# Generated by Django 5.0.7 on 2024-08-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0002_task_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
