# Generated by Django 5.0.7 on 2024-08-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0005_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='custom_reminder',
            field=models.IntegerField(blank=True, help_text='Custom reminder time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder',
            field=models.CharField(choices=[('15_min', '15 minutes before'), ('30_min', '30 minutes before'), ('1_hour', '1 hour before'), ('2_hours', '2 hours before'), ('1_day', '1 day before'), ('1_week', '1 week before'), ('custom', 'Custom')], default='30_min', max_length=20),
        ),
    ]
